name: Cypress CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Change directory
        run: cd app
      - name: Install Dependencies
        run: npm install
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
